### ISSUE TITLE
Drag-and-Drop

### ISSUE THREAD

**Issue by js3289** [SuitPotato/HolaMundoCapstone#9]
Drag and drop example questions to be demo'd to Dr. Schairer.

**Comment by SuitPotato** [comment]
https://bevacqua.github.io/dragula/

**Comment by js3289** [comment]
Basics added, working for words in sentences.

Still need:
     Limit the number of words per accept box
     Allow choices to be put into multiple accepting boxes.

**Comment by SuitPotato** [comment]
Needs fine tuning overall now.
